<!--==== Work Header Image ====-->
<section id="projects" class="wrap projects"></br></br></br></br>
    <div class="projects-body">
        <div class="container">
            <div class="row col-md-offset-7">
                <div class="col-md-8">
                    <h1 class="brand-heading">Projects</h1>
                    <p class="intro-text pull-left">Where Impact is Made</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--== Feature Notes ========================================
-
-
- Really Good-Looking Lightbox: (http://goo.gl/O9ih9T)
- Really Good-Looking Div-prior-to-pop-up: (http://goo.gl/KeB24A)
- Responsive youtube modal: http://goo.gl/rEcfyT
-
=======================================================-->

<!--==== Work Content ====-->
<section class="container content-section">
<!-- <div id="demoLightbox" class="lightbox hide fade"  tabindex="-1" role="dialog" aria-hidden="true">
<div class='lightbox-content'>
    <img src="../img/tedxpurdueu.jpg">
    <div class="lightbox-caption"><p>Your caption here</p></div>
</div>
</div> -->
    <div class="row">
        <div id="wrap" class="wrap">
        <!-- == Projects == -->
<!--         <div class="container">
            <div class="row"> -->
                <h1>Projects</h1>
                <p>For the time being, until I get the models working, please view my <a href="https://github.com/alex-cory" class="proj-main-clr">Github</a> or go to the <strong class="proj-main-clr">projects</strong> portion of my <a href="https://www.linkedin.com/in/alexcory" class="proj-main-clr">LinkedIn</a> located all the way at the bottom.  Although not all of my projects are on Github or LinkedIn, at least you can see some of the projects I've worked on.</p>
        </div>
    </div>
    <div class="row">
        <?php // Thumbnail Hover without Javascript     (resource: http://goo.gl/5Jpg09) ?>
        <?php

        /**
         * GET ALL REPOSITORIES:
         *
         * @param  string $username     [the username of the person]
         * @return array  $repositories [contains an array of repositories]
         */
        function getAllRepositories()
        {
            // This file is generated by Composer
            if (file_exists('./vendor/autoload.php')) {
                require_once "./vendor/autoload.php";
                $client = new \Github\Client();
                $repositories = $client->api('user')->repositories(GITHUB_USERNAME);
                $repositories = addImagesFromRepos($repositories);
                return $repositories;
            } else {
                return 'the file path must be off';
            }
        }


        /**
         * ADD IMAGES FROM REPOS:
         *
         * @param  string $username [the username of the person]
         * @param  object $repos    [these contain all the data for each repo]
         * @return string $images   [url for the image!]
         */
        function addImagesFromRepos($repos)
        {
            $count = 0;
            // $images = array();
            foreach ($repos as $repo) {
                $repos[$count]['image'] = "https://raw.githubusercontent.com/" . GITHUB_USERNAME . "/". $repo['name'] . "/" . $repo['default_branch'] . "/" . $repo['name'] . ".png";
                $count++;
            }
            return $repos;
        }


        /**
         * URL EXISTS:
         *
         * @param  string  $url [the url to be tested]
         * @return boolean      [true or false]
         */
        function url_exists($url)
        {
            $file = $url;
            $file_headers = @get_headers($file);
            if($file_headers[0] == 'HTTP/1.1 404 Not Found') {
                $exists = false;
            } else {
                $exists = true;
            }
            return $exists;
        }

        function addLiveDemo()
        {
            # code...
        }
        // d($repositories);
        // d($repositories);
         ?>

        <?php $repositories = getAllRepositories(); ?>
        <?php foreach ($repositories as $repository): ?>
            <div class="col-xs-6 col-sm-4 col-md-3">
                <div id="wrap" class="thumbnail2 wrap text-center">
                    <div class="thumbnail2">
                        <div class="thumbnail">
                            <a href="#myModal">
                                <div class="caption">
                                    <h4><?php echo $repository['name']; ?></h4>
                                    <p>short thumbnail description</p>
                                    <br>
                                    <!-- </button> -->
                                    <!-- <p><a href="" class="label label-danger">Zoom</a>
                                    <a href="" class="label label-default">Download</a></p> -->
                                    <!-- End MODAL HERE -->
                                </div>
                            </a>
                            <!-- alfred-workflows_repo_image -->
                            <div class="repo_image" style="background-image: url('<?php echo url_exists($repository['image']) ? $repository['image'] : "http://lorempixel.com/400/300/sports/4/"; ?>'); background-size: cover; background-position: center; height: 195px;"></div>
                        </div>
                        <div class="panel-footer text-center">
                            <a href="<?php echo $repository['html_url']; ?>/archive/master.zip"><span class="glyphicon glyphicon-download"></span></a>
                            <a href="<?php echo $repository['html_url']; ?>"><span class="fa fa-github"></span></a>
                            <a href="#live_preview"><span class="fa fa-play-circle-o"></span></a>
                            <a href="mailto:?subject=Found%20our%20next%20software%20engineer&body=Check%20out%20this%20sweet%20project%20he%20did%21%20Yep...%20We%27re%20totally%20hiring%20him.%20
<?php echo $repository['html_url']; ?>"><span class="glyphicon glyphicon-share-alt"></span></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="m-top-10">
                    <div class="panel-image text-center">
                        <div class="repo_img_modal" style="background-image: url('<?php echo url_exists($repository['image']) ? $repository['image'] : "http://lorempixel.com/400/300/sports/4/"; ?>');"></div>
                        <!-- <img src="http://666a658c624a3c03a6b2-25cda059d975d2f318c03e90bcf17c40.r92.cf1.rackcdn.com/unsplash_52d09387ae003_1.JPG" class="panel-image-preview" /> -->
                        <!-- <img class="repo_image" id="<?php echo $repository['name']; ?>" src="<?php echo $repository['image']; ?>" onload="checkImage(this)" onerror="" alt="<?php echo $repository['name']; ?>"> -->
                        <label for="toggle-1"></label>
                        <div class="panel-footer footer-cool text-center">
                            <a href="<?php echo $repository['html_url']; ?>/archive/master.zip">
                                <span class="glyphicon glyphicon-download"></span>
                                <span class="modal-subtext">Download</span>
                            </a>
                            <a href="<?php echo $repository['html_url']; ?>">
                                <span class="fa fa-github"></span>
                                <span class="strong modal-subtext">Github</span>
                            </a>
                            <a href="#live_preview">
                                <span class="fa fa-play-circle-o"></span>
                                <span class="modal-subtext">Live Demo</span>
                            </a>
                            <a href="#share">
                                <span class="glyphicon glyphicon-share-alt"></span>
                                <span class="modal-subtext">Share</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
</section></br>