<!--==== Work Header Image ====-->
<section id="projects" class="wrap projects"></br></br></br></br>
    <div class="projects-body">
        <div class="container">
            <div class="row col-md-offset-7">
                <div class="col-md-8">
                    <h1 class="brand-heading">Projects</h1>
                    <p class="intro-text pull-left">Where Impact is Made</p>
                </div>
            </div>
        </div>
    </div>
</section>
<!--== Feature Notes ========================================
-
-
- Really Good-Looking Lightbox: (http://goo.gl/O9ih9T)
- Really Good-Looking Div-prior-to-pop-up: (http://goo.gl/KeB24A)
- Responsive youtube modal: http://goo.gl/rEcfyT
-
=======================================================-->

<!--==== Work Content ====-->
<section class="container content-section">
<!-- <div id="demoLightbox" class="lightbox hide fade"  tabindex="-1" role="dialog" aria-hidden="true">
<div class='lightbox-content'>
    <img src="../img/tedxpurdueu.jpg">
    <div class="lightbox-caption"><p>Your caption here</p></div>
</div>
</div> -->
    <div class="row">
        <div id="wrap" class="wrap">
        <!-- == Projects == -->
<!--         <div class="container">
            <div class="row"> -->
                <h1>Projects</h1>
                <p>For the time being, until I get the models working, please view my <a href="https://github.com/alex-cory" class="proj-main-clr">Github</a> or go to the <strong class="proj-main-clr">projects</strong> portion of my <a href="https://www.linkedin.com/in/alexcory" class="proj-main-clr">LinkedIn</a> located all the way at the bottom.  Although not all of my projects are on Github or LinkedIn, at least you can see some of the projects I've worked on.</p>
        </div>
    </div>
    <div class="row">
        <?php // Thumbnail Hover without Javascript     (resource: http://goo.gl/5Jpg09) ?>
        <?php

        function getAllRepositories()
        {
            // This file is generated by Composer
            require_once 'vendor/autoload.php';

            $client = new \Github\Client();
            $repositories = $client->api('user')->repositories('alex-cory');

            return $repositories;
        }

        function hasLiveDemo()
        {
            # code...
        }

        function getLiveDemo($value='')
        {
            # code...
        }

        // $github = new GithubModel;
        $repositories = getAllRepositories();
        // d($repositories);

         ?>

        <?php foreach ($repositories as $repository): ?>
            <div class="col-xs-6 col-sm-4 col-md-3">
                <div id="wrap" class="wrap text-center">
                    <div class="thumbnail2">
                        <div class="thumbnail">
                            <a href="#myModal">
                                <div class="caption">


                                        <h4><?php echo $repository['name']; ?></h4>
                                        <p>short thumbnail description</p>
                                        <br>
                                    <!-- </button> -->
                                    <!-- <p><a href="" class="label label-danger">Zoom</a>
                                    <a href="" class="label label-default">Download</a></p> -->
                                    <!-- End MODAL HERE -->
                                </div>
                            </a>
                            <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                        </div>
                        <div class="panel-footer text-center">
                            <a href="<?php echo $repository['html_url']; ?>/archive/master.zip"><span class="glyphicon glyphicon-download"></span></a>
                            <a href="<?php echo $repository['html_url']; ?>"><span class="fa fa-github"></span></a>
                            <a href="#live_preview"><span class="fa fa-play-circle-o"></span></a>
                            <a href="mailto:?subject=Found%20our%20next%20software%20engineer&body=Check%20out%20this%20sweet%20project%20he%20did%21%20Yep...%20We%27re%20totally%20hiring%20him.%20
<?php echo $repository['html_url']; ?>"><span class="glyphicon glyphicon-share-alt"></span></a>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Modal -->
            <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                <div class="m-top-10">
                    <div class="panel-image text-center">
                        <img src="http://666a658c624a3c03a6b2-25cda059d975d2f318c03e90bcf17c40.r92.cf1.rackcdn.com/unsplash_52d09387ae003_1.JPG" class="panel-image-preview" />
                        <label for="toggle-1"></label>
                        <div class="panel-footer footer-cool text-center">
                            <a href="<?php echo $repository['html_url']; ?>/archive/master.zip">
                                <span class="glyphicon glyphicon-download"></span>
                                <span class="modal-subtext">Download</span>
                            </a>
                            <a href="<?php echo $repository['html_url']; ?>">
                                <span class="fa fa-github"></span>
                                <span class="modal-subtext">Github</span>
                            </a>
                            <a href="#live_preview">
                                <span class="fa fa-play-circle-o"></span>
                                <span class="modal-subtext">Live Demo</span>
                            </a>
                            <a href="#share">
                                <span class="glyphicon glyphicon-share-alt"></span>
                                <span class="modal-subtext">Share</span>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
<!--         <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">


                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
                                    <br>
                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">

                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
<br>

                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">


                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
                                    <br>

                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <?php // Portfolio using Panels No JavaScrip   (resource: http://goo.gl/KeB24A) ?>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">


                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
                                    <br>

                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">


                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
                                    <br>

                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">


                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
                                    <br>

                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-xs-6 col-sm-4 col-md-3">
            <div id="wrap" class="wrap text-center">
                <div class="thumbnail2">
                    <div class="thumbnail">
                        <a href="#myModal">
                            <div class="caption">


                                    <h4>Thumbnail Headline</h4>
                                    <p>short thumbnail description</p>
                                    <br>

                            </div>
                        </a>
                        <img src="http://lorempixel.com/400/300/sports/4/" alt="...">
                    </div>
                    <div class="panel-footer text-center">
                        <a href="#download"><span class="glyphicon glyphicon-download"></span></a>
                        <a href="#facebook"><span class="fa fa-facebook"></span></a>
                        <a href="#twitter"><span class="fa fa-twitter"></span></a>
                        <a href="#share"><span class="glyphicon glyphicon-share-alt"></span></a>
                    </div>
                </div>
            </div>
        </div>
    </div> -->
</section></br>