<?php

# Models are going to be grabbing stuff from the database or putting stuff to the database

class GithubModel // extends Model
{
	// function getRepository($rID)
	// {
	// 	// perform query
	// 	//$results = $this->db->getrow($sql, array($pID, $p));
	// 	$results = $this->db->getrow($sql, array($pID));

	// 	// $this->message = (! empty($results)) ? "Successfully got the post! :)" : "Sowwy! Couldn't find the post. :(";
	// 	$repository = $results;

	// 	return $repository;
	// }

	/**
	 * Description:
	 * This will return an array of all the repositories. Accessible from within the $repositories array.
	 *
	 * @return array   $repositories this holds all the repositories
	 */
	public function getAllRepositories()
	{
		// This file is generated by Composer
		require_once '../vendor/autoload.php';

		$client = new \Github\Client();
		$repositories = $client->api('user')->repositories('alex-cory');

		return $repositories;
	}
}
$github = new GithubModel;


$repositories = $github->getAllRepositories();

// d($repositories);
